<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?=$this->title?></title>
</head>
<body>
	<h1>
		<?=$this->title?>
	</h1>
	<table>
		<tr>
			<td>
				<h2>
					<a href="<?=$this->getInsertLink()?>">Insert</a>
				</h2>
			</td>
			<td>
			<?=$this->getSearchForm()?>
			</td>
		</tr>
	</table>	
<table border="1">
<?=$this->renderHTMLTableContent($this->records)?>
</table>
</body>
</html>
